#!/usr/bin/env python3
"""Create a small synthetic reflectogram ZIP archive for calibration demos.

The demo archive is intentionally generated by ReflectoGen itself. It is not a
validation dataset and should not be interpreted as a field or proprietary data
source. Its purpose is to provide a lightweight end-to-end calibration smoke
example for users and continuous integration.
"""

from __future__ import annotations

import argparse
import tempfile
import zipfile
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from reflectogen import GeneratorConfig, make_name, render_reflectogram, synthesize_signal


def build_demo_archive(out_path: Path) -> None:
    cases = [
        ("Rectangular", 10.0, 10.5, -20),
        ("Round", 10.0, 10.5, -20),
        ("Triangular", 10.0, 10.5, -20),
        ("Rectangular", 15.0, 16.0, 25),
        ("Round", 15.0, 16.0, 25),
        ("Triangular", 15.0, 16.0, 25),
    ]
    cfg = GeneratorConfig(render_width=300, render_height=100)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        for shape, start, end, pct in cases:
            _, signal, _, _ = synthesize_signal(cfg, shape, start, end, pct)
            img_path = tmp_dir / make_name(shape, start, end, pct)
            render_reflectogram(cfg, signal).save(img_path)
        with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for img_path in sorted(tmp_dir.glob("*.png")):
                zf.write(img_path, arcname=img_path.name)


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a small demo reflectogram archive for ReflectoGen calibration.")
    parser.add_argument("--out", default="outputs/demo_legacy_reflectograms.zip", help="Output ZIP path.")
    args = parser.parse_args()
    build_demo_archive(Path(args.out))
    print(f"[DONE] Demo archive written to: {args.out}")


if __name__ == "__main__":
    main()
